apiVersion: v1
kind: Service
metadata:
  name: emulatorjs-service
  labels:
    apps: emulatorjs
spec:
  selector:
    app: emulatorjs
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: admin
      protocol: TCP
      port: 3000
      targetPort: 3000
